project:
  type: website
  output-dir: docs

website:
  # google-analytics: "G-9QW2N0QB7G"
  title: "Entomology 3927/5927"
  favicon: media/web-favicon.png
  navbar:
    logo: media/ent-3927-hex.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - schedule.qmd
      - href: content/content-index.qmd
        text: Content
      - href: workshop/workshop-index.qmd
        text: Workshops
      - resources.qmd
    right:
      - href: media/ento3927-syllabus_fall2026.pdf # providing a relative file path to a pdf will open up a browser-based pdf viewer when clicked
        text: Course Syllabus
        icon: file-pdf
        target: _blank # opens link (or page) in a new browser tab
      - icon: github # add icons as navbar buttons
        href: https://github.com/entomology-3927-5927
        target: _blank
      - icon: envelope
        href: mailto:jhemberg@umn.edu
  page-footer:
    background: light # or `dark`
    left: Copyright 2025, Jeremy Hemberger
    # center: |
    #   Background image: Large milkweed bug nymph aggregation (<i>Oncopeltus fasciatus</i>), 2017
    right: Built with [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
  sidebar:
    - title: "Workshops"
      style: "docked"
      search: false
      background: light
      contents: 
        - section: "Overview"
          contents:
            - workshop/workshop-index.qmd
        - section: "Module 1: Introduction to Data Science and R"
          contents:
            - text: "Week 1: Intro to data science and R"
              file: workshop/w1-workshop.qmd
            - text: "Week 2: Project organization, RStudio, your 'devenv'"
              file: workshop/w2-workshop.qmd
        - section: "Module 2: Git and GitHub fundamentals"
          contents:
            - text: "Week 3: Go on, Git!"
              file: workshop/w3-workshop.qmd
            - text: "Week 4: Go on, Git it onto GitHub"
              file: workshop/w4-workshop.qmd
        - section: "Module 3: Basic data wrangling and visualization in R"
          contents:
            - text: "Week 5: Data wrangling 1"
              file: workshop/w5-workshop.qmd
            - text: "Week 6: Data wrangling 2"
              file: workshop/w6-workshop.qmd
            - text: "Week 7: Data visualization: theory and practice"
              file: workshop/w7-workshop.qmd
        - section: "Module 4: Automation, functions, and scaling"
          contents:
            - text: "Week 8: Functions and automation"
              file: workshop/w8-workshop.qmd
            - text: "Week 9: Batching, scaling work/pipelines"
              file: workshop/w9-workshop.qmd
        - section: "Module 5: Getting data from databases and data management"
          contents:
            - text: "Week 10: Databases, web APIs, web-scraping"
              file: workshop/w10-workshop.qmd
            - text: "Week 11: Data mangagement, metadata, documentation"
              file: workshop/w11-workshop.qmd
        - section: "Module 6: Open Science Framework and transparent science"
          content:
            - text: "Week 12: Open Science Framework"
              file: workshop/w12-workshop.qmd
        - section: "Module 7: Integration and application"
          content:
            - text: "Week 13: In-class work day/overflow"
              file: workshop/w13-workshop.qmd
            - text: "Week 14: Final Presentations"
              file: workshop/w14-workshop.qmd
    - title: "Content"
      style: "docked"
      search: false
      background: light
      contents: 
        - section: "Overview"
          contents:
            - content/content-index.qmd
        - section: "Module 1: Introduction to Data Science and R"
          contents:
            - text: "Week 1: Intro to data science and R"
              file: content/w1-content.qmd
            - text: "Week 2: Project organization, RStudio, your 'devenv'"
              file: content/w2-content.qmd
        - section: "Module 2: Git and GitHub fundamentals"
          contents:
            - text: "Week 3: Go on, Git!"
              file: content/w3-content.qmd
            - text: "Week 4: Go on, Git it onto GitHub"
              file: content/w4-content.qmd
        - section: "Module 3: Basic data wrangling and visualization in R"
          contents:
            - text: "Week 5: Data wrangling 1"
              file: content/w5-content.qmd
            - text: "Week 6: Data wrangling 2"
              file: content/w6-content.qmd
            - text: "Week 7: Data visualization: theory and practice"
              file: content/w7-content.qmd
        - section: "Module 4: Automation, functions, and scaling"
          contents:
            - text: "Week 8: Functions and automation"
              file: content/w8-content.qmd
            - text: "Week 9: Batching, scaling work/pipelines"
              file: content/w9-content.qmd
        - section: "Module 5: Getting data from databases and data management"
          contents:
            - text: "Week 10: Databases, web APIs, web-scraping"
              file: content/w10-content.qmd
            - text: "Week 11: Data mangagement, metadata, documentation"
              file: content/w11-content.qmd
        - section: "Module 6: Open Science Framework and transparent science"
          content:
            - text: "Week 12: Open Science Framework"
              file: content/w12-content.qmd
        - section: "Module 7: Integration and application"
          content:
            - text: "Week 13: In-class work day/overflow"
              file: content/w13-content.qmd
            - text: "Week 14: Final Presentations"
              file: content/w14-content.qmd


format:
  html:
    theme: 
      - styles.scss
    # css: styles.scss
    toc: true
    mainfont: Roboto Condensed
    page-layout: full
    highlight-style: ayu

editor: visual

  