---
title: "Overview of workshops + basic info"
sidebar: true
toc: true
page-layout: full
date: last-modified
date-format: long
---

------------------------------------------------------------------------

Here, you'll find the virtual companion to all of our hands-on workshops for the semester. These will be the same as your physical hand-outs, but I know many folks prefer to have them up on their screens as they work through the activities.

The purpose of these workshops is to practice applying the topics that we discuss in lecture using real-world examples and data. The associated data files for each lab are linked in the `Frontmatter` section atop each page (all the files are also located [here](link%20here)). Over the semester, we'll explore some of the frustrations and challenges of working with bio/ecological data (of which there are many!), but together we'll conquer them, setting y'all up for success in analyzing, interpreting, and sharing your own data.

A total of 8 of the workshops will have an assignment/report that will be peer reviewed (i.e., evaluated). The first three to four weeks will be devoted to a primer of using R/RStudio, basic programming, project management, and the use of Git and GitHub (which we will use extensively in this class to manage course materials and feedback). 

## Downloading, installing, and setting up R and RStudio

For this course, we'll be using R and R Studio to do all of our work. You also have the option of using the Posit Cloud service for workshops and assignments. It's essentially an online virtual machine to run RStudio in your browser. This will avoid version issues, package incompatibilities, and Mac vs Windows challenges that you might otherwise face. This is a paid service we'll be using for class and it will expire after our semester concludes, so I also encourage you to install R and R Studio on your own machines if you haven't already. Click on the buttons below to install both R (the language, or engine that enables our analyses to be performed) and RStudio (the shell, or vessel that the engine of R sits in and gives us the nifty features to manage files, version history, and write pretty and readable code).

[{{< fa cloud >}} [Launch Posit Cloud](https://posit.cloud/){style="color: white !important;"}]{.btn .btn-primary role="button"} [{{< fa brands r-project title="R Project">}} [Download R](https://cran.r-project.org/){style="color: white !important;"}]{.btn .btn-primary role="button"} [{{< fa registered >}} [Download RStudio](https://posit.co/download/rstudio-desktop/){style="color: white !important;"}]{.btn .btn-primary role="button"}



## Completing and submitting workshop reports

In labs, we'll be writing code in a couple of different ways, but primarily what I will be recommending is using an R Notebook to write, annotate, and interpret your code. R Notebooks are a type of Markdown file where we can mix formatted text, code chunks, and a whole bunch of other goodies. R Notebooks help to organize your code into sections and subsections, and will let you write about the output directly in the document rather than creating a Word document (shudder...). We'll go through this a bit more in the first lab, but take a look at the following links to learn a bit more about R Notebooks and R Markdown.

- [Writing code in R notebooks](https://bookdown.org/yihui/rmarkdown/notebook.html)
- [R Notebook (Markdown) cheatsheet](https://posit.co/wp-content/uploads/2022/10/rmarkdown-1.pdf)